### ISSUE TITLE
Why not javax.inject?

### ISSUE THREAD

**Issue by wellingtoncosta** [IVIanuu/injekt#361]
Hello,

It's not an issue, but it's a curiosity. In the past years we had a lot of framework implementations for dependency injection pattern, and most of these implementations uses a common API for declaring dependencies, injection point and so on. By convenience, these implementations uses the `javax.inject.*` constructs, which brings a common and ease-to-use approach, which facilitates adoption from developers that uses other solutions based on the `javax.inject.*` API.

Did you considered to use the `javax.inject.*` constructs rather than creating you own annotation API?

At all, your implementation based on Kotlin Compiler Plugin is very very interesting.

**Comment by IVIanuu** [comment]
Hi,

My library uses it's own annotations because it's pretty different from libraries like Dagger. It is more similar to Scala's implicit parameters (http://dotty.epfl.ch/docs/reference/contextual/givens.html).

The term "given" is a better match for what it does in comparison to "inject"

It's also possible to mark type parameter's or local variable's as @Given so i'm not sure if the @Inject annotation has all the required annotation targets to work in those cases.

Glad that you find it interesting.

**Comment by wellingtoncosta** [comment]
Thanks for clarification! I don't know Scala, but it looks interesting. The syntax of "given" statement really matches better.
